using System;
using System.IO;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace MCTwinStudio.Services
{
    public class BehaviorGeneratorService
    {
        private readonly string _outputDir;

        public BehaviorGeneratorService()
        {
            _outputDir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Assets", "Behaviors");
        }

        public async Task<string> GenerateAsync(string prompt)
        {
            // In a real app, this calls OpenAI. 
            // Here, we simulate the "AI Architect" using heuristics.
            
            await Task.Delay(1000); // Simulate "Thinking"

            // Simplify name
            string safePrompt = Regex.Replace(prompt, @"[^a-zA-Z0-9]", "");
            string scriptName = "AI_" + safePrompt;
            if (scriptName.Length > 20) scriptName = scriptName.Substring(0, 20);

            string code = "";

            if (prompt.ToLower().Contains("spin") || prompt.ToLower().Contains("rotate"))
            {
                code = GenerateSpin(scriptName);
            }
            else if (prompt.ToLower().Contains("jump") || prompt.ToLower().Contains("hop"))
            {
                code = GenerateJump(scriptName);
            }
            else if (prompt.ToLower().Contains("scale") || prompt.ToLower().Contains("grow"))
            {
                code = GenerateScale(scriptName);
            }
            else
            {
                code = GenerateGeneric(scriptName, prompt);
            }

            string path = Path.Combine(_outputDir, scriptName + ".js");
            await File.WriteAllTextAsync(path, code);
            return scriptName;
        }

        private string GenerateSpin(string name)
        {
            return $@"// Generated by MCTwin AI
if (!window.MCTwinBehaviors) window.MCTwinBehaviors = {{}};

window.MCTwinBehaviors[""{name}""] = {{
    onTick: (node, args, time) => {{
        const speed = parseFloat(args.Speed || ""2.0"");
        node.rotation.y += 0.05 * speed;
    }}
}};";
        }

        private string GenerateJump(string name)
        {
             return $@"// Generated by MCTwin AI
if (!window.MCTwinBehaviors) window.MCTwinBehaviors = {{}};

window.MCTwinBehaviors[""{name}""] = {{
    onInteract: (node, args) => {{
        if (node.metadata.isJumping) return;
        node.metadata.isJumping = true;
        const startY = node.position.y;
        
        BABYLON.Animation.CreateAndStartAnimation(
            ""jump_{{name}}"", node, ""position.y"", 60, 30, 
            startY, startY + 2, 0, new BABYLON.QuadraticEase(),
            () => {{
                 BABYLON.Animation.CreateAndStartAnimation(
                    ""land_{{name}}"", node, ""position.y"", 60, 30, 
                    startY + 2, startY, 0, new BABYLON.QuadraticEase(),
                    () => node.metadata.isJumping = false
                );
            }}
        );
    }}
}};";
        }

        private string GenerateScale(string name)
        {
             return $@"// Generated by MCTwin AI
if (!window.MCTwinBehaviors) window.MCTwinBehaviors = {{}};

window.MCTwinBehaviors[""{name}""] = {{
    onInteract: (node, args) => {{
        const target = node.scaling.x > 1.5 ? 1.0 : 2.0;
        BABYLON.Animation.CreateAndStartAnimation(
            ""scale_{{name}}"", node, ""scaling"", 60, 30, 
            node.scaling, new BABYLON.Vector3(target, target, target), 
            0
        );
    }}
}};";
        }

        private string GenerateGeneric(string name, string prompt)
        {
            return $@"// Generated by MCTwin AI
// Prompt: {prompt}
if (!window.MCTwinBehaviors) window.MCTwinBehaviors = {{}};

window.MCTwinBehaviors[""{name}""] = {{
    onInteract: (node, args) => {{
        console.log(""AI Behavior {name} triggered!"");
        // AI note: I heard '{prompt}' but I am a heuristic simulation.
        // Defaulting to a wobble.
        node.rotation.z = Math.random() * 0.5;
    }}
}};";
        }
    }
}
